Squashed commit of the following:
commit b1aaa556d251996c66ef60225af52ad08c2a5bbf
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 17:34:40 2025 +0200

    yolo: redirect?

commit fb2a7849ea747b56aebf258e3d06ccdfe0690f25
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 17:28:10 2025 +0200

    use svelte depends

commit c7e623fe94201556c3f4a2cff0ff63390687da23
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 17:21:05 2025 +0200

    update without full page refresh

commit f0e29d86635b56b3780767831085a1cfc31d4d1f
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 17:15:00 2025 +0200

    always sync from server

commit ac159be76a9c1e0b93c8421bbb194dbfac76a665
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 17:08:21 2025 +0200

    yolo svelte 5 rework language merging

commit e9a7e3c7e9935265a309af0c1f3e018b0e6333d9
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 16:59:57 2025 +0200

    Update +layout.server.ts

commit 5c7d22756cb35ad62081a6c77f657742d9bb8729
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 16:45:46 2025 +0200

    cleanup garbage

commit ac92a89f73a4924fc8abf1c1d84b4ccbca90bcae
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 16:42:05 2025 +0200

    cleanup language suggtion logging

commit 9b6dd7f10fb951aa0e2ddbdbc21856f7f69ec107
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 16:30:50 2025 +0200

    onmount

commit 578d078302df04f8f9830a7305a342d82ed5a2c6
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 16:20:34 2025 +0200

    more debug fun :D

commit 9e62c6701a8d27cf027d5738e07fdcf9414cc06b
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 16:11:58 2025 +0200

    log more

commit ab9e2252fc9ee15e89138b4a81cc72d3873670ea
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 15:31:44 2025 +0200

    user pref sync debug

commit cbd10cb41ec94ff4030f3b6d1ae779f990bcc709
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 13:38:35 2025 +0200

    WIP: copy arrays to save changes safely?

commit f6c269abed3a0f1d0ea473704bf5348e92127e19
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:47:29 2025 +0200

    yolo sync user langs from server

commit 4248b1d59a1b294ae292f5674e994dae1a499f2e
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:45:07 2025 +0200

    WIP prevent local override server user prefs

commit 7cd76061ba425d4978ff9fce7012125428397394
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:27:38 2025 +0200

    debug language erase

commit 46dd10c6b141f9de8a1a53866589dadcadd995bf
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:20:32 2025 +0200

    blur

commit dd20832d858d4685b5e69df9ec4c1efed164cac2
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:17:06 2025 +0200

    smoother language suggestion

commit 6f8bc91bfe3ff22ecc43b5228c5ac1203cd61fa3
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:10:36 2025 +0200

    languagesuggestions.svelte

commit 2e58ff129b0372e1f6e8fa11a92d6b6d6e2fe17c
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:05:58 2025 +0200

    LanguageSuggestions.svelte

commit f294f723da139bfc5a4dd20565dbbc276dd984de
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 12:03:59 2025 +0200

    fixed locally: language suggestion

commit 031cf44ee1b5cf5196a0ac3026d7e808810ea9d7
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 11:47:15 2025 +0200

    Update +layout.svelte

commit 8cd45fec3636ff93c1111b4bce44941384e216db
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 11:37:29 2025 +0200

    remove suggestedLanguages

commit d696c93a8bab9d37522fb7c4385fbea7fdcab6e2
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 11:31:26 2025 +0200

    simplify userSuggestions

commit a532cf4b73813f6c753e6fe9db27981677a7b63c
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 11:14:19 2025 +0200

    debug suggestions

commit 2a8c02108a4bf7d077819c53dd7b0eab7832d1b3
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 11:14:10 2025 +0200

    no fake colorization

commit 648b518beb93d5bdeef4c775fbf2091a81a96734
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 11:07:03 2025 +0200

    onMount load language suggestions

commit 850b9d522e42fb12b3e804442664cf8183add8d6
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 11:01:09 2025 +0200

    suggest languages

commit 3f6f506dce98365dc9fd710a0d3b20062bb50668
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 10:31:49 2025 +0200

    more suggestions

commit 8b22c5ae7f54028ef761c00552d0e9cd73127530
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 01:50:50 2025 +0200

    WIP language suggestions

commit 20a9483ee4c1890312b02ccb808ca41439b703f1
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 01:38:24 2025 +0200

    WIP language suggestion

commit 1fc07197d6b6a928207c9c05eedf4ac4d6959da8
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 01:31:15 2025 +0200

    ensureEmailChecked

commit 91d0e89d933afb170c2f19af80f51f918b1944f3
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 01:27:56 2025 +0200

    Update +page.svelte

commit 94bb847320514089c8560c7482d1084e39393992
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 01:17:24 2025 +0200

    yolo remember language selection on login

commit f513aff1a6199e2a9516e4d41b16e17f67af5a41
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Mon May 26 01:05:02 2025 +0200

    Create user-add-auth.md

commit 9b420fbf56bfaa9a12ad70874f8ffeb593d65e63
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 01:00:28 2025 +0200

    Update +page.svelte

commit 404c14387aaefcc5992052910938ea25e66ae984
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:57:03 2025 +0200

    oninput

commit 5f6d9196fa2cd862eed4f07c0b1ccb7d29297fbc
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:50:56 2025 +0200

    user layout

commit 6580471b1f4846d3a43b0ce5e7458e871f7df973
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:50:35 2025 +0200

    Update +page.svelte

commit 3a44aac5278dc6844cb03d48c1b41ffa9697c687
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:46:18 2025 +0200

    fix check email

commit ab3ca402bb304589a65421f079e28f43a2130d96
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:43:57 2025 +0200

    WIP combined login/register

commit be6c897429734605d2b28f21e485ee9b33dd429d
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:26:42 2025 +0200

    WIP /auth

commit 6eb1f1562e2a3189cee49454f592691b680f4735
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:08:55 2025 +0200

    password button reactovity

commit fcac0358017bf24ed04b41379ef613dd30d9ffbb
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:04:11 2025 +0200

    move password input

commit 8a6389e09510c4c0abc276759de514d006aca0ba
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Mon May 26 00:00:47 2025 +0200

    WIP login/register ui compact update

commit 2f5a5cdcd4cc53e89d3c2e981826a53c36041c51
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:35:04 2025 +0200

    cleanup logs

commit 2c3c5ddea4a8c803dbd1a2b9c8eb49de58991b5b
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:34:56 2025 +0200

    cleanup logs

commit 3b3273e121df0ebfa10b9dac5fa9fad8e503c938
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Sun May 25 23:28:25 2025 +0200

    again

commit 5e9e6ab6407173cbd31011d83a59aa3453dc4dfe
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:25:18 2025 +0200

    yolo debug

commit cfb121b0384658a32c67161a5428903a44b60e75
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:20:49 2025 +0200

    Update passkey-auth.js

commit 3ecba14e1d4d84bb1e05c029bd74c16f2f89fdb5
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:17:30 2025 +0200

    yolo Buffer is not defined

commit eacdf8fe624dc572689a587d3abf32b20880acbb
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:13:32 2025 +0200

    log login

commit 7e4c48b5a22137506d91932c6e8878693e89cc81
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:00:50 2025 +0200

    llm help

commit 706a921ca4d053cdb5fc38294c45c7f9c01d239c
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Sun May 25 23:00:08 2025 +0200

    yolo invalid attestation object encoding. WIP oslo

    oslo clientside and serverside to prevent discrepancies hopefully

commit 75d839cb67e810e7d9814b0ebd80a09114e35297
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 18:27:23 2025 +0200

    regex

commit 03c34b3238897eb10c627bf362d748b61eac51bd
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 16:28:03 2025 +0200

    passkey debug

commit b4d90d30f76f4fff1b14178538afcf8550fde916
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 16:03:32 2025 +0200

    WIP: buffer error, learn from lucia example

commit dfc03049a717c4baf5b33ba3a15843f0361cc10b
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 15:57:46 2025 +0200

    WIP buffer error

commit 31251d78915e78a14b0974c83069c040d9aa9a77
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 15:57:32 2025 +0200

    local dev passkey fallback

commit 4535f3f29a322768f0811815401b5be9fca2b6e7
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 15:41:39 2025 +0200

    debug passkey: doesn't ask for biometric auth

commit 65925e4b6f9bcbe2fd274f3a5fed72c577f0c390
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 15:17:53 2025 +0200

    get rpId from env

commit 3de4d54b6703e393b254c1aa96fb8ff4ebfa3c5e
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 14:58:41 2025 +0200

    WIP passkey

commit 60952bd06b2fa13ce1ee8b223770d16cccb2452b
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Fri May 23 14:35:02 2025 +0200

    invalidateAll?

commit 0d2993edf425a45b7b5f9714a25d07d54e5930d4
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 17:21:25 2025 +0200

    WIP sessions

commit 2d3267d7583443809bcdf519702961ebec3da880
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 17:11:15 2025 +0200

    UserNav

commit d31f042dcb926aed79e45cecbecb532a23a6d72e
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 15:12:32 2025 +0200

    wip fix login broken by previous commit

commit 27aa7404f45dbe4410426d7da98396d961ede46a
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 14:59:02 2025 +0200

    auth without refresh?

commit b31eb3192c088403404b5f8531f007b5989676c3
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 14:54:53 2025 +0200

    sync user prefs?

commit 7751426db25ffe7202fae2c12e5188a1497c91e6
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 14:48:37 2025 +0200

    logout

commit 71580f5310df9979d8f29a7e2f62c806edec670c
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 14:33:13 2025 +0200

    add user info

commit d60cf4eb6cb8e7617b84ecd99c9cb7b461745208
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 14:07:08 2025 +0200

    login

commit 02c48717be1c221530a4ee601b5c49a48444ae5a
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 13:32:04 2025 +0200

    Update bun.lockb

commit 41c3f27862eedafd00574fb9864d15145e76c8da
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 13:31:39 2025 +0200

    remove prism

commit bc906898f2d55acf334dfc482eb7c2136a9c6d93
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 12:57:50 2025 +0200

    Update SettingsButton.svelte

commit 2c2b6c986ed52da0565cb8756b79f7387e159f55
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Wed May 21 12:50:08 2025 +0200

    no prism in component

commit f5565c9cdd87cd31e7347f067b46fbe698ecce8c
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Tue May 20 22:26:38 2025 +0200

    serverside debug highlighting

commit 559a91c9af8882c77dff5e233eae8cea88d9bc5a
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Tue May 20 21:42:06 2025 +0200

    Update users.js

commit fab0cdfcd2e7d091886ce76f6065e3d5ef86c9f7
Author: Morgan <2504532+mrgnw@users.noreply.github.com>
Date:   Tue May 20 21:42:04 2025 +0200

    delete handler

commit 265a5b05071412b8e4a1c93e3ef821ea8a69a2aa
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Thu May 15 12:08:41 2025 +0200

    WIP build update

commit f76465d7426079cf024cfbd07be26dd6a7ee8d3e
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Thu May 15 11:59:22 2025 +0200

    WIP db: translation history

commit d4a70d14493f7f0bc5ede3391761345cf9d9a6dc
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 23:59:37 2025 +0200

    WIP user prefs

commit 00a6a9f7a12fd459560b6a42d63c3775d53878b9
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 23:46:39 2025 +0200

    username

commit 746d2e1f7d618c7c24579b1bd7a15d4f61be7598
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 23:38:50 2025 +0200

    WIP  D1_ERROR: Wrong number of parameter bindings for SQL query.

    D1_ERROR: Wrong number of parameter bindings for SQL query.

commit b82c0a020394704864b8c35eb360174ef637a488
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 23:08:42 2025 +0200

    WIP debugging

commit 3c8c6a03ffafd116c97011c9bc50505abba5bf4a
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 23:02:20 2025 +0200

    WIP

commit dfc91144e0ba59fed151172a3c1662e34b0ea1f8
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 22:55:35 2025 +0200

    Update auth.js

commit ddb4186b2ffdf2b808956ea1384528ba8e39f572
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 22:53:29 2025 +0200

    WIP

commit df8c9b9ddafb0e93adb27d87abefc25393a9ffab
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 22:50:14 2025 +0200

    WIP

commit 413c2ac5bf60291bbfbd9c559a4134ab54a0b471
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 22:34:45 2025 +0200

    WIP d1 basic auth

commit 03bea11603db965cb5789819c2e8cd257418ce66
Author: Morgan Williams <morgan.williams.ext@allianz-trade.com>
Date:   Wed May 14 22:24:08 2025 +0200

    deprecate